name: Android CI

on:
  pull_request:
    branches:
      - '*'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build Gradle
        run: ./gradlew build 
      
      - name: Bulid App 
        run: ./gradlew assembleDebug
        
  test:
    runs-on: macos-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest
        
      - name: Run UI Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          target: google_apis
          ram-size: 2048M
          cores: 2
          avd-name: test avd
          disable-animations: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb devices
            ./gradlew connectedDebugAndroidTest
